# Generated by Django 3.0.3 on 2020-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
